apiVersion: v1
kind: Namespace
metadata:
  name: tap-gui
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: tap-gui
  name: tap-gui-viewer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tap-gui-read-k8s
subjects:
  - kind: ServiceAccount
    namespace: tap-gui
    name: tap-gui-viewer
roleRef:
  kind: ClusterRole
  name: k8s-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-reader
rules:
  - apiGroups: ['']
    resources: ['pods', 'services', 'configmaps']
    verbs: ['get', 'watch', 'list']
  - apiGroups: ['apps']
    resources: ['deployments', 'replicasets']
    verbs: ['get', 'watch', 'list']
  - apiGroups: ['autoscaling']
    resources: ['horizontalpodautoscalers']
    verbs: ['get', 'watch', 'list']
  - apiGroups: ['networking.k8s.io']
    resources: ['ingresses']
    verbs: ['get', 'watch', 'list']
  - apiGroups: ['networking.internal.knative.dev']
    resources: ['serverlessservices']
    verbs: ['get', 'watch', 'list']
  - apiGroups: [ 'autoscaling.internal.knative.dev' ]
    resources: [ 'podautoscalers' ]
    verbs: [ 'get', 'watch', 'list' ]
  - apiGroups: ['serving.knative.dev']
    resources:
      - configurations
      - revisions
      - routes
      - services
    verbs: ['get', 'watch', 'list']